{{- $uiTarget := default "front" .Values.ui.target | lower }}
{{- if eq $uiTarget "front" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-front
  ports:
    - name: http
      port: {{ .Values.front.servicePort }}
      targetPort: 80
{{- else if eq $uiTarget "web" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-web
  ports:
    - name: http
      port: {{ .Values.web.servicePort }}
      targetPort: 80
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-api
  ports:
    - name: http
      port: {{ .Values.api.servicePort }}
      targetPort: {{ .Values.api.containerPort | default 8080 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-postgres
  ports:
    - name: postgres
      port: {{ .Values.postgres.port | default 5432 }}
      targetPort: {{ .Values.postgres.port | default 5432 }}
