ui:
  target: front

front:
  servicePort: 80
  image:
    repository: acrecommercedev629.azurecr.io/front
    tag: dev-latest
    pullPolicy: IfNotPresent

web:
  servicePort: 80
  image:
    repository: acrecommercedev629.azurecr.io/web
    tag: dev-latest
    pullPolicy: IfNotPresent


api:
  servicePort: 80
  containerPort: 8080
  image:
    repository: acrecommercedev629.azurecr.io/api
    tag: dev-latest
    pullPolicy: IfNotPresent
  allowedOrigins:
    - https://dapang.live
    - https://www.dapang.live
    - http://localhost:5173

postgres:
  image:
    repository: postgres
    tag: "16"
    pullPolicy: IfNotPresent
  port: 5432
  database: appdb
  username: app
  password: app_pw
  storage:
    enabled: false
    size: 1Gi
    className: ""

certManager:
  enabled: true
  clusterIssuerName: letsencrypt-prod
  email: zhonghaoyang629@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory
  privateKeySecretName: letsencrypt-prod-account-key

ingress:
  enabled: true
  className: nginx
  host: dapang.live
  apiHost: api.dapang.live
  enableConfigurationSnippet: false
  tls:
    enabled: true
    secretName: dapang-live-tls
