name: Build & Deploy Front + API to AKS (dev)

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "front/**"
      - "api/**"
      - "helm/**"
      - ".github/workflows/build-and-deploy.yml"

permissions:
  id-token: write
  contents: read

env:
  RG: rg-ecommerce-dev
  AKS: aks-ecommerce-dev
  NAMESPACE: ecommerce
  RELEASE: ecommerce
  CHART_PATH: ./helm/ecommerce
  ACR_NAME: acrecommercedev629
  IMAGE_NAME: front
  API_IMAGE_NAME: api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. set image tag from git sha
      - name: Set image tag from git sha
        run: echo "IMAGE_TAG=dev-${GITHUB_SHA::7}" >> $GITHUB_ENV

      # 3. login to Azure (OIDC)
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 4. login to ACR
      - name: Login to ACR
        run: az acr login -n $ACR_NAME

      # 5. build & push Angular front image
      - name: Build and push front image
        run: |
          ACR_LOGIN_SERVER=$(az acr show -n $ACR_NAME --query loginServer -o tsv)
          echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER"

          docker build \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:${IMAGE_TAG} \
            ./front

          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:${IMAGE_TAG}

      # 5b. build & push API image
      - name: Build and push API image
        run: |
          ACR_LOGIN_SERVER=$(az acr show -n $ACR_NAME --query loginServer -o tsv)
          echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER"

          docker build \
            -t $ACR_LOGIN_SERVER/$API_IMAGE_NAME:${IMAGE_TAG} \
            ./api

          docker push $ACR_LOGIN_SERVER/$API_IMAGE_NAME:${IMAGE_TAG}

      # 6. set AKS context
      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.RG }}
          cluster-name: ${{ env.AKS }}

      # 7. deploy with Helm (use the SAME image tag)
      - name: Helm upgrade/install
        run: |
          helm upgrade --install $RELEASE $CHART_PATH \
            --namespace $NAMESPACE \
            --create-namespace \
            --set front.image.tag=${IMAGE_TAG} \
            --set ui.target=front \
            --set api.image.tag=${IMAGE_TAG}

      # 8. show status
      - name: Show status
        run: |
          kubectl get pods -n $NAMESPACE
          kubectl get svc -n $NAMESPACE
          kubectl get ingress -n $NAMESPACE
